### ISSUE TITLE
Error when installing Cadabra2

### ISSUE THREAD

**Issue by AndreasSchachner** [kpeeters/homebrew-repo#2]
**The following issue appeared when installing Cadabra2 on my Mac using homebrew. Is the package compatible with macOS Big Sur and Python3.9?**

**ERROR MESSAGE:**

==> make install
Last 15 lines from /Users/andreasschachner/Library/Logs/Homebrew/cadabra2/02.make:
make[2]: *** [frontend/gtkmm/CMakeFiles/cadabra2-gtk.dir/ImageView.cc.o] Error 1
1 error generated.
make[2]: *** [frontend/gtkmm/CMakeFiles/cadabra2-gtk.dir/SelectFileDialog.cc.o] Error 1
1 error generated.
make[2]: *** [frontend/gtkmm/CMakeFiles/cadabra2-gtk.dir/CodeInput.cc.o] Error 1
1 error generated.
make[2]: *** [frontend/gtkmm/CMakeFiles/cadabra2-gtk.dir/NotebookWindow.cc.o] Error 1
make[1]: *** [frontend/gtkmm/CMakeFiles/cadabra2-gtk.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX shared library cadabra2.so
cd /tmp/cadabra2-20201207-66852-1yxaceq/cadabra2-master/core && /usr/local/Cellar/cmake/3.19.1/bin/cmake -E cmake_link_script CMakeFiles/cadabra2.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -o cadabra2.so -install_name @rpath/cadabra2.so CMakeFiles/cadabra2.dir/InstallPrefix.cc.o CMakeFiles/cadabra2.dir/DataCell.cc.o CMakeFiles/cadabra2.dir/CdbPython.cc.o CMakeFiles/cadabra2.dir/ExNode.cc.o CMakeFiles/cadabra2.dir/ProgressMonitor.cc.o CMakeFiles/cadabra2.dir/Bridge.cc.o CMakeFiles/cadabra2.dir/Adjform.cc.o CMakeFiles/cadabra2.dir/Algorithm.cc.o CMakeFiles/cadabra2.dir/Cleanup.cc.o CMakeFiles/cadabra2.dir/Combinatorics.cc.o CMakeFiles/cadabra2.dir/Compare.cc.o CMakeFiles/cadabra2.dir/DisplayBase.cc.o CMakeFiles/cadabra2.dir/DisplayMMA.cc.o CMakeFiles/cadabra2.dir/DisplayTeX.cc.o CMakeFiles/cadabra2.dir/DisplaySympy.cc.o CMakeFiles/cadabra2.dir/DisplayTerminal.cc.o CMakeFiles/cadabra2.dir/TerminalStream.cc.o CMakeFiles/cadabra2.dir/Exceptions.cc.o CMakeFiles/cadabra2.dir/Exchange.cc.o CMakeFiles/cadabra2.dir/Functional.cc.o CMakeFiles/cadabra2.dir/Hash.cc.o CMakeFiles/cadabra2.dir/IndexIterator.cc.o CMakeFiles/cadabra2.dir/IndexClassifier.cc.o CMakeFiles/cadabra2.dir/Kernel.cc.o CMakeFiles/cadabra2.dir/Linear.cc.o CMakeFiles/cadabra2.dir/Parser.cc.o CMakeFiles/cadabra2.dir/PreClean.cc.o CMakeFiles/cadabra2.dir/PreProcessor.cc.o CMakeFiles/cadabra2.dir/Props.cc.o CMakeFiles/cadabra2.dir/PythonException.cc.o CMakeFiles/cadabra2.dir/Stopwatch.cc.o CMakeFiles/cadabra2.dir/Storage.cc.o CMakeFiles/cadabra2.dir/Symbols.cc.o CMakeFiles/cadabra2.dir/SympyCdb.cc.o CMakeFiles/cadabra2.dir/YoungTab.cc.o CMakeFiles/cadabra2.dir/modules/xperm_new.cc.o CMakeFiles/cadabra2.dir/__/libs/whereami/whereami.c.o CMakeFiles/cadabra2.dir/__/libs/base64/base64.cc.o CMakeFiles/cadabra2.dir/algorithms/canonicalise.cc.o CMakeFiles/cadabra2.dir/algorithms/collect_components.cc.o CMakeFiles/cadabra2.dir/algorithms/collect_factors.cc.o CMakeFiles/cadabra2.dir/algorithms/collect_terms.cc.o CMakeFiles/cadabra2.dir/algorithms/combine.cc.o CMakeFiles/cadabra2.dir/algorithms/complete.cc.o CMakeFiles/cadabra2.dir/algorithms/decompose.cc.o CMakeFiles/cadabra2.dir/algorithms/decompose_product.cc.o CMakeFiles/cadabra2.dir/algorithms/distribute.cc.o CMakeFiles/cadabra2.dir/algorithms/drop_weight.cc.o CMakeFiles/cadabra2.dir/algorithms/einsteinify.cc.o CMakeFiles/cadabra2.dir/algorithms/eliminate_kronecker.cc.o CMakeFiles/cadabra2.dir/algorithms/eliminate_metric.cc.o CMakeFiles/cadabra2.dir/algorithms/eliminate_vielbein.cc.o CMakeFiles/cadabra2.dir/algorithms/epsilon_to_delta.cc.o CMakeFiles/cadabra2.dir/algorithms/evaluate.cc.o CMakeFiles/cadabra2.dir/algorithms/expand.cc.o CMakeFiles/cadabra2.dir/algorithms/expand_delta.cc.o CMakeFiles/cadabra2.dir/algorithms/expand_diracbar.cc.o CMakeFiles/cadabra2.dir/algorithms/expand_power.cc.o CMakeFiles/cadabra2.dir/algorithms/explicit_indices.cc.o CMakeFiles/cadabra2.dir/algorithms/factor_in.cc.o CMakeFiles/cadabra2.dir/algorithms/factor_out.cc.o CMakeFiles/cadabra2.dir/algorithms/fierz.cc.o CMakeFiles/cadabra2.dir/algorithms/flatten_product.cc.o CMakeFiles/cadabra2.dir/algorithms/flatten_sum.cc.o CMakeFiles/cadabra2.dir/algorithms/indexsort.cc.o CMakeFiles/cadabra2.dir/algorithms/integrate_by_parts.cc.o CMakeFiles/cadabra2.dir/algorithms/join_gamma.cc.o CMakeFiles/cadabra2.dir/algorithms/keep_terms.cc.o CMakeFiles/cadabra2.dir/algorithms/lower_free_indices.cc.o CMakeFiles/cadabra2.dir/algorithms/lr_tensor.cc.o CMakeFiles/cadabra2.dir/algorithms/map_sympy.cc.o CMakeFiles/cadabra2.dir/algorithms/meld.cc.o CMakeFiles/cadabra2.dir/algorithms/order.cc.o CMakeFiles/cadabra2.dir/algorithms/product_rule.cc.o CMakeFiles/cadabra2.dir/algorithms/reduce_delta.cc.o CMakeFiles/cadabra2.dir/algorithms/rename_dummies.cc.o CMakeFiles/cadabra2.dir/algorithms/rewrite_indices.cc.o CMakeFiles/cadabra2.dir/algorithms/simplify.cc.o CMakeFiles/cadabra2.dir/algorithms/sort_product.cc.o CMakeFiles/cadabra2.dir/algorithms/sort_spinors.cc.o CMakeFiles/cadabra2.dir/algorithms/sort_sum.cc.o CMakeFiles/cadabra2.dir/algorithms/split_gamma.cc.o CMakeFiles/cadabra2.dir/algorithms/split_index.cc.o CMakeFiles/cadabra2.dir/algorithms/substitute.cc.o CMakeFiles/cadabra2.dir/algorithms/sym.cc.o CMakeFiles/cadabra2.dir/algorithms/tab_dimension.cc.o CMakeFiles/cadabra2.dir/algorithms/tab_basics.cc.o CMakeFiles/cadabra2.dir/algorithms/take_match.cc.o CMakeFiles/cadabra2.dir/algorithms/replace_match.cc.o CMakeFiles/cadabra2.dir/algorithms/unwrap.cc.o CMakeFiles/cadabra2.dir/algorithms/unzoom.cc.o CMakeFiles/cadabra2.dir/algorithms/untrace.cc.o CMakeFiles/cadabra2.dir/algorithms/vary.cc.o CMakeFiles/cadabra2.dir/algorithms/young_project.cc.o CMakeFiles/cadabra2.dir/algorithms/young_project_product.cc.o CMakeFiles/cadabra2.dir/algorithms/young_project_tensor.cc.o CMakeFiles/cadabra2.dir/algorithms/zoom.cc.o CMakeFiles/cadabra2.dir/properties/Accent.cc.o CMakeFiles/cadabra2.dir/properties/AntiCommuting.cc.o CMakeFiles/cadabra2.dir/properties/AntiSymmetric.cc.o CMakeFiles/cadabra2.dir/properties/Commuting.cc.o CMakeFiles/cadabra2.dir/properties/CommutingAsProduct.cc.o CMakeFiles/cadabra2.dir/properties/CommutingAsSum.cc.o CMakeFiles/cadabra2.dir/properties/CommutingBehaviour.cc.o CMakeFiles/cadabra2.dir/properties/Coordinate.cc.o CMakeFiles/cadabra2.dir/properties/DAntiSymmetric.cc.o CMakeFiles/cadabra2.dir/properties/Depends.cc.o CMakeFiles/cadabra2.dir/properties/DependsInherit.cc.o CMakeFiles/cadabra2.dir/properties/Derivative.cc.o CMakeFiles/cadabra2.dir/properties/Determinant.cc.o CMakeFiles/cadabra2.dir/properties/Diagonal.cc.o CMakeFiles/cadabra2.dir/properties/DifferentialForm.cc.o CMakeFiles/cadabra2.dir/properties/DiracBar.cc.o CMakeFiles/cadabra2.dir/properties/Distributable.cc.o CMakeFiles/cadabra2.dir/properties/EpsilonTensor.cc.o CMakeFiles/cadabra2.dir/properties/ExteriorDerivative.cc.o CMakeFiles/cadabra2.dir/properties/FilledTableau.cc.o CMakeFiles/cadabra2.dir/properties/GammaMatrix.cc.o CMakeFiles/cadabra2.dir/properties/GammaTraceless.cc.o CMakeFiles/cadabra2.dir/properties/ImaginaryI.cc.o CMakeFiles/cadabra2.dir/properties/ImplicitIndex.cc.o CMakeFiles/cadabra2.dir/properties/Indices.cc.o CMakeFiles/cadabra2.dir/properties/Integer.cc.o CMakeFiles/cadabra2.dir/properties/InverseMetric.cc.o CMakeFiles/cadabra2.dir/properties/KroneckerDelta.cc.o CMakeFiles/cadabra2.dir/properties/LaTeXForm.cc.o CMakeFiles/cadabra2.dir/properties/Matrix.cc.o CMakeFiles/cadabra2.dir/properties/Metric.cc.o CMakeFiles/cadabra2.dir/properties/NonCommuting.cc.o CMakeFiles/cadabra2.dir/properties/NumericalFlat.cc.o CMakeFiles/cadabra2.dir/properties/PartialDerivative.cc.o CMakeFiles/cadabra2.dir/properties/RiemannTensor.cc.o CMakeFiles/cadabra2.dir/properties/SatisfiesBianchi.cc.o CMakeFiles/cadabra2.dir/properties/SelfAntiCommuting.cc.o CMakeFiles/cadabra2.dir/properties/SelfCommuting.cc.o CMakeFiles/cadabra2.dir/properties/SelfNonCommuting.cc.o CMakeFiles/cadabra2.dir/properties/SortOrder.cc.o CMakeFiles/cadabra2.dir/properties/Spinor.cc.o CMakeFiles/cadabra2.dir/properties/Symbol.cc.o CMakeFiles/cadabra2.dir/properties/Symmetric.cc.o CMakeFiles/cadabra2.dir/properties/Tableau.cc.o CMakeFiles/cadabra2.dir/properties/TableauBase.cc.o CMakeFiles/cadabra2.dir/properties/TableauInherit.cc.o CMakeFiles/cadabra2.dir/properties/TableauSymmetry.cc.o CMakeFiles/cadabra2.dir/properties/Trace.cc.o CMakeFiles/cadabra2.dir/properties/Traceless.cc.o CMakeFiles/cadabra2.dir/properties/Vielbein.cc.o CMakeFiles/cadabra2.dir/properties/Weight.cc.o CMakeFiles/cadabra2.dir/properties/WeightInherit.cc.o CMakeFiles/cadabra2.dir/properties/WeylTensor.cc.o CMakeFiles/cadabra2.dir/__/libs/jsoncpp/jsoncpp.cpp.o CMakeFiles/cadabra2.dir/pythoncdb/py_algorithms.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_ex.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_globals.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_helpers.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_kernel.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_module.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_packages.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_progress.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_properties.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_stopwatch.cc.o CMakeFiles/cadabra2.dir/pythoncdb/py_tableau.cc.o  -undefined dynamic_lookup -flto /usr/local/lib/libgmpxx.dylib /usr/local/lib/libgmp.dylib /usr/local/lib/libboost_system-mt.dylib 
cd /tmp/cadabra2-20201207-66852-1yxaceq/cadabra2-master/core && /usr/bin/strip -x /tmp/cadabra2-20201207-66852-1yxaceq/cadabra2-master/core/cadabra2.so
[ 96%] Built target cadabra2
make: *** [all] Error 2

**Comment by kpeeters** [comment]
I currently do not have a Big Sur machine, so this is going to be interesting to debug. Did I correctly understand that you attempted to install with homebrew (using `brew install cadabra2`)?  If so, can you try building from source instead, with the current version available from github?

**Comment by AndreasSchachner** [comment]
Thank you for the quick response. I installed Cadabra2 from GitHub today without any issues. But I'm still not sure though what's going wrong in the installation via homebrew.

**Comment by kpeeters** [comment]
The homebrew version is still on 2.3.0, and there are probably some fixes which have gone in in the meantime to sort out those build problems. I'll do an update again once 2.3.6 is out.
