### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by StefanoDeAngelis** [kpeeters/homebrew-repo#3]
The following issue appeared when installing cadabra2 both via homebrew and from source on Mac.
-

cmake -DENABLE_MATHEMATICA=OFF .

Last 15 lines from /Users/stefanodeangelis/Library/Logs/Homebrew/cadabra2/01.cmake:
  Configuring client-server

-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'glibmm-2.4'
--   No package 'glibmm-2.4' found
CMake Error at /usr/local/Cellar/cmake/3.19.2/share/cmake/Modules/FindPkgConfig.cmake:553 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.19.2/share/cmake/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  cmake/modules/FindGLIBMM.cmake:8 (pkg_check_modules)
  client_server/CMakeLists.txt:18 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cadabra2-20201224-55089-1v4g5jx/cadabra2-master/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kpeeters/homebrew-repo/issues

**Comment by kpeeters** [comment]
Make sure that you have linked the following kegs: `glibmm@2.64`, `atkmm@2.28`, `cairomm@1.14`, `pangomm@2.42`. For some reason which I do not understand, the default `glibmm` package now links version 2.68, which belongs to `gtk4` rather than `gtk3`, and unlinks `2.64`. So try

    brew link glibmm@2.64 cairomm@1.14 pangomm@2.42 atkmm@2.28

and then `brew upgrade` again. Let me know if that works.

**Comment by StefanoDeAngelis** [comment]
After having linked also sigc-2.0 with

`brew link libsigc++@2`

everything works fine.
